import '@/styles/main.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/Common/Header'
import Footer from '@/components/Common/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Vogaro株式会社',
    default: 'Vogaro株式会社'
  },
  description: 'Generated by create next app',
  openGraph: {
    url: 'https://example.com',
    siteName: 'Vogaro株式会社',
    images: [
      {
        url: 'https://example.com/og.png',
        width: 800,
        height: 600,
      },
      {
        url: 'https://example.com/og-alt.png',
        width: 1800,
        height: 1600,
        alt: '代替テキスト',
      },
    ],
    locale: 'en_US',
    type: 'website',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        </body>
    </html>
  )
}
